type Day={date:string;slots:string[]};
type Info={calendar?:boolean;meetingReady?:boolean;duration?:number;meetingUrl?:string};
const el=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const form=el<HTMLFormElement>('book-form'), submit=el<HTMLButtonElement>('submit');
let info:Info|null=null, days:Day[]=[], selected='',mode='book',week=0,busy=false,id=crypto.randomUUID().replaceAll('-','');
const dateLabel=(value:string)=>new Date(value).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo',month:'long',day:'numeric',weekday:'short',hour:'2-digit',minute:'2-digit'});
function error(message=''){el('error').textContent=message;el('error').hidden=!message}
async function api(action:string,body?:unknown){const r=await fetch('/api/booking/'+action,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});if(!r.headers.get('content-type')?.includes('application/json'))throw Error('接続を確認できません。時間をおいてお試しください。');const d=await r.json();if(!r.ok)throw Error(d.error||'受付を完了できませんでした');return d}
function update(){submit.disabled=busy||!info||(mode==='book'&&(!selected||!info.calendar||info.meetingReady===false));submit.firstElementChild!.textContent=busy?'確認しています…':mode==='book'?'この日時で予約する':'相談内容を送信する';el<HTMLButtonElement>('mode-book').disabled=busy||!info?.calendar||info?.meetingReady===false;el<HTMLButtonElement>('mode-inquiry').disabled=busy;}
function setMode(value:string){mode=value;selected='';id=crypto.randomUUID().replaceAll('-','');el('calendar-block').hidden=mode!=='book';el('mode-book').setAttribute('aria-pressed',String(mode==='book'));el('mode-inquiry').setAttribute('aria-pressed',String(mode==='inquiry'));form.querySelector<HTMLTextAreaElement>('textarea')!.required=mode==='inquiry';el('message-label').textContent=mode==='inquiry'?'必須':'任意';el('submit-note').textContent=mode==='book'?'予約確定後、カレンダーからご案内が届きます。':'内容を確認し、メールでご連絡します。';error();render();update()}
function render(){const perPage=matchMedia('(max-width:440px)').matches?3:7;const max=Math.max(0,Math.ceil(days.length/perPage)-1);week=Math.min(week,max);const view=days.slice(week*perPage,(week+1)*perPage);const container=el('availability');container.replaceChildren();if(view.length){const short=(s:string)=>new Date(s+'T12:00:00+09:00').toLocaleDateString('ja-JP',{month:'long',day:'numeric'});el('week-label').textContent=short(view[0].date)+'〜'+short(view.at(-1)!.date)}for(const day of view){const col=document.createElement('div');col.className='day';const heading=document.createElement('div');heading.className='day-heading';const date=new Date(day.date+'T12:00:00+09:00');const num=document.createElement('b');num.textContent=String(date.getDate());const weekday=document.createElement('span');weekday.textContent=date.toLocaleDateString('ja-JP',{weekday:'short'});heading.append(num,weekday);col.append(heading);if(!day.slots.length){const empty=document.createElement('p');empty.className='no-slots';empty.textContent='空きなし';col.append(empty)}for(const time of day.slots){const b=document.createElement('button');b.type='button';b.textContent=new Date(time).toLocaleTimeString('ja-JP',{timeZone:'Asia/Tokyo',hour:'2-digit',minute:'2-digit'});b.setAttribute('aria-label',dateLabel(time));b.setAttribute('aria-pressed',String(time===selected));b.onclick=()=>{if(busy)return;selected=time;error();render();update()};col.append(b)}container.append(col)}el<HTMLButtonElement>('prev-week').disabled=week===0;el<HTMLButtonElement>('next-week').disabled=week>=max;el('selected').textContent=selected?'選択中：'+dateLabel(selected)+'（日本時間）':'日時を選んで、下のフォームへお進みください。'}
async function load(){error();el('retry').hidden=true;busy=true;update();try{info=await api('info');el('duration').textContent=(info?.duration||30)+'分';if(info?.calendar&&info.meetingReady!==false){days=(await api('availability')).days||[];el('status').textContent='';render();if(!days.some(d=>d.slots.length))el('status').textContent='現在、今後14日間の空き枠はありません。メッセージでご相談ください。'}else{setMode('inquiry');el('status').textContent='日時予約は現在準備中です。メッセージでご相談いただけます。'}}catch(e){error((e as Error).message);el('retry').hidden=false;}finally{busy=false;el('availability').setAttribute('aria-busy','false');update()}}
el('mode-book').onclick=()=>setMode('book');el('mode-inquiry').onclick=()=>setMode('inquiry');el('prev-week').onclick=()=>{week--;render()};el('next-week').onclick=()=>{week++;render()};el('retry').onclick=load;matchMedia('(max-width:440px)').addEventListener('change',()=>{week=0;render()});
form.onsubmit=async(e)=>{e.preventDefault();if(busy||submit.disabled)return;busy=true;update();error();const data=new FormData(form);try{const result=await api(mode,{name:data.get('name'),company:data.get('company'),email:data.get('email'),message:data.get('message'),website:data.get('website'),privacy:data.get('privacy')==='on',start:selected,id});el('success-message').textContent=result.message;el('success-time').textContent=selected?dateLabel(selected)+'（日本時間）':'';const link=el<HTMLAnchorElement>('meeting-link');link.hidden=mode!=='book'||!info?.meetingUrl;if(info?.meetingUrl){const u=new URL(info.meetingUrl);if(u.protocol==='https:'&&u.hostname.endsWith('.larksuite.com'))link.href=u.href;else link.hidden=true;}el('booking-content').hidden=true;el('success').hidden=false;el('success').scrollIntoView({behavior:'auto',block:'center'});}catch(e){error((e as Error).message)}finally{busy=false;update()}};
void load();
